name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install x86_64-pc-windows-gnu target
      run: rustup target add x86_64-pc-windows-gnu
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build -r --verbose
    - name: Run tests
      run: cargo test --verbose
